# ansible/playbook.yml
---
- name: install and configure prom & grafana
  hosts: monitoring
  become: yes
  tasks:
    # update package repository
    - name: update apt cache
      apt:
        update_cache: yes

    # install docker
    - name: install docker
      apt:
        name: docker.io
        state: present

    - name: enable & start docker services
      systemd:
        name: docker
        enabled: yes
        state: started

    # pull prom docker image
    - name: pull prom docker image
      command: docker pull prom/prometheus

    # pull grafana docker image
    - name: pull grafana docker image
      command: docker pull grafana/grafana

    # create prom configuration file
    - name: create prom configuration directory
      file:
        path: /home/ubuntu/prometheus
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: create prom configuration file
      copy:
        dest: /home/ubuntu/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: "prometheus"
              static_configs:
                - targets: ["localhost:9090"]
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    # run prom container
    - name: run prom container
      command: >
        docker run -d --name prometheus
        -p 9090:9090
        -v /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        prom/prometheus

    # run grafana container
    - name: run grafana container
      command: >
        docker run -d --name grafana
        -p 3000:3000
        grafana/grafana

    # install python and pip
    - name: install python, pip & venv
      apt:
        name:
          - python3
          - python3-pip
          - python3.12-venv
        state: present

    # install git
    - name: install git
      apt:
        name: git
        state: present

    # clone mlflow git repo
    - name: clone mlflow git repo
      git:
        repo: "https://github.com/Lem0nRavioli/fashion_cnn_vs_dense_streamlit"
        dest: /home/ubuntu/mlflow
        version: master
        update: yes # if repo exists, update it
      # args:
      #   chdir: /home/ubuntu/mlflow

    # fix permissions for mlflow directory
    - name: ensure ownership of mlflow directory
      file:
        path: /home/ubuntu/mlflow
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: build docker image from git repo Dockerfile
      command: >
        docker build . -t mlflow-boston-housing
      args:
        chdir: /home/ubuntu/mlflow


    - name: run mlflow docker container
      command: >
        docker run -d -p 5000:5000 mlflow-boston-housing


    #     # Find the latest MLflow model artifacts
    # - name: Find the latest MLflow model artifacts
    #   shell: |
    #     find /home/ubuntu/mlflow/mlruns/0/ -type d -name "model" | sort | tail -1
    #   register: latest_model_path

    # - name: Debug latest_model_path.stdout
    #   debug:
    #     var: latest_model_path.stdout

    # # Serve the MLflow model using the correct path
    # - name: Serve the trained MLflow model
    #   become_user: ubuntu
    #   shell: >
    #     /home/ubuntu/mlflow_env/bin/mlflow models serve
    #     --model-uri {{ latest_model_path.stdout }}
    #     --port 8888 --no-conda
    #   args:
    #     executable: /bin/bash



